"""Manual reference-point metadata for downstream physical validation only."""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path
from typing import Any

import numpy as np
import yaml


VALIDATION_COORDINATE_SYSTEM = "wass_rectified_computational_cam0__input_right"


@dataclass(frozen=True)
class FrozenReferenceFrame:
    """Identity of one exported image tied to a frozen reconstruction result."""

    label: str
    target_time_s: float
    cam1_frame_id: str
    cam1_pts_s: float
    canonical_rotation_deg: int
    image_sha256: str
    width_px: int
    height_px: int
    coordinate_system: str


def validate_frozen_frame_identity(
    record: dict[str, Any], result_metadata: dict[str, Any], pair_metadata: dict[str, Any]
) -> None:
    """Cross-check one manual-reference record against both frozen identities."""
    expected = (
        str(record["source_frame_id"]),
        float(record["source_pts_s"]),
        float(record["target_time_s"]),
    )
    result = (
        str(result_metadata["right_frame_id"]),
        float(result_metadata["right_timestamp_s"]),
        float(result_metadata["requested_time_s"]),
    )
    pair = (
        str(pair_metadata["right_frame_id"]),
        float(pair_metadata["right_timestamp_s"]),
        float(pair_metadata["requested_time_s"]),
    )
    if expected != result or expected != pair:
        raise ValueError("FROZEN_FRAME_IDENTITY_MISMATCH")


def file_sha256(path: str | Path) -> str:
    """Hash an exported reference without modifying it."""
    digest = sha256()
    with Path(path).open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest().upper()


def require_direct_validation_coordinates(
    *, source_coordinate_system: str, target_coordinate_system: str, source_size: tuple[int, int], target_size: tuple[int, int]
) -> None:
    """Allow direct clicks only for identical coordinate systems and sizes.

    This deliberately rejects resolution scaling, homographies and raw/canonical
    pixels that lack a verified mapping to the frozen pixel–XYZ coordinates.
    """
    if source_coordinate_system != target_coordinate_system:
        raise ValueError("CAM1_VALIDATION_PIXEL_MAPPING_NOT_AVAILABLE")
    if source_size != target_size:
        raise ValueError("unverified resolution scaling is forbidden")


def _opencv() -> Any:
    try:
        import cv2  # type: ignore[import-not-found]
    except ImportError as error:
        raise RuntimeError(
            "canonical-to-rectified mapping requires the OpenCV Python bindings; "
            "install opencv-python-headless without changing calibration data"
        ) from error
    return cv2


def load_frozen_cam1_rectification(mapping_file: str | Path) -> tuple[np.ndarray, ...]:
    """Load the frozen two-stage cam1-to-WASS validation mapping.

    WASS first undistorts the input with ``K1/D1`` and ``P=K1``.  Its stereo
    executable then rectifies that prepared image with zero distortion.  The
    second-stage ``R/P`` values in this file were generated by the frozen WASS
    OpenCV 4.6 runtime and verified pixel-for-pixel against its saved image.
    """
    data = yaml.safe_load(Path(mapping_file).read_text(encoding="utf-8"))
    if data.get("coordinate_mapping") != "canonical_cam1_to_wass_rectified_computational_cam0":
        raise ValueError("frozen mapping coordinate identity mismatch")
    if data.get("wass_role_mapping") != {"computational_cam0": "input_right_cam1"}:
        raise ValueError("frozen WASS role-swap metadata is incompatible")
    prepare = data["prepare_undistortion"]
    rectify = data["stereo_rectification"]
    intrinsic = np.asarray(prepare["K1"], dtype=np.float64)
    distortion = np.asarray(prepare["D1"], dtype=np.float64)
    rotation = np.asarray(rectify["R_computational_cam0"], dtype=np.float64)
    projection = np.asarray(rectify["P_computational_cam0"], dtype=np.float64)
    if intrinsic.shape != (3, 3) or distortion.ndim != 1 or rotation.shape != (3, 3) or projection.shape != (3, 4):
        raise ValueError("frozen cam1 rectification matrix schema is invalid")
    arrays = (intrinsic, distortion, rotation, projection)
    if any(not np.all(np.isfinite(array)) for array in arrays):
        raise ValueError("frozen cam1 rectification contains non-finite values")
    return arrays


def canonical_cam1_to_rectified(
    points_px: np.ndarray,
    *,
    mapping_file: str | Path,
    wass_auto_swap: bool,
) -> np.ndarray:
    """Map canonical cam1 pixels to the frozen computational rectified image."""
    if not wass_auto_swap:
        raise ValueError("WASS role-swap identity is required for this frozen baseline")
    points = np.asarray(points_px, dtype=np.float64)
    if points.ndim != 2 or points.shape[1] != 2 or points.shape[0] == 0 or not np.all(np.isfinite(points)):
        raise ValueError("canonical cam1 points must have finite shape [point,2]")
    intrinsic, distortion, rotation, projection = load_frozen_cam1_rectification(mapping_file)
    cv2 = _opencv()
    prepared = cv2.undistortPoints(
        points.reshape(-1, 1, 2), intrinsic, distortion, R=np.eye(3), P=intrinsic
    )
    mapped = cv2.undistortPoints(
        prepared, intrinsic, np.zeros_like(distortion), R=rotation, P=projection
    )
    return np.asarray(mapped, dtype=np.float64).reshape(-1, 2)


def canonical_rectified_roundtrip_error(
    points_px: np.ndarray,
    *,
    mapping_file: str | Path,
    image_size: tuple[int, int],
    wass_auto_swap: bool,
) -> np.ndarray:
    """Check canonical->rectified points against OpenCV's forward remap fields."""
    mapped = canonical_cam1_to_rectified(
        points_px, mapping_file=mapping_file, wass_auto_swap=wass_auto_swap
    )
    intrinsic, distortion, rotation, projection = load_frozen_cam1_rectification(mapping_file)
    cv2 = _opencv()
    prepare_x, prepare_y = cv2.initUndistortRectifyMap(
        intrinsic, distortion, np.eye(3), intrinsic, image_size, cv2.CV_32FC1
    )
    rectify_x, rectify_y = cv2.initUndistortRectifyMap(
        intrinsic, np.zeros_like(distortion), rotation, projection, image_size, cv2.CV_32FC1
    )
    width, height = image_size
    source = np.asarray(points_px, dtype=np.float64)
    errors: list[float] = []
    for original, rectified in zip(source, mapped):
        x, y = rectified
        if not (0 <= x < width - 1 and 0 <= y < height - 1):
            continue
        x0, y0 = int(np.floor(x)), int(np.floor(y))
        ax, ay = x - x0, y - y0
        weights = np.asarray([(1 - ax) * (1 - ay), ax * (1 - ay), (1 - ax) * ay, ax * ay])
        prepared_x = float(np.dot(weights, [rectify_x[y0, x0], rectify_x[y0, x0 + 1], rectify_x[y0 + 1, x0], rectify_x[y0 + 1, x0 + 1]]))
        prepared_y = float(np.dot(weights, [rectify_y[y0, x0], rectify_y[y0, x0 + 1], rectify_y[y0 + 1, x0], rectify_y[y0 + 1, x0 + 1]]))
        if not (0 <= prepared_x < width - 1 and 0 <= prepared_y < height - 1):
            continue
        px0, py0 = int(np.floor(prepared_x)), int(np.floor(prepared_y))
        bx, by = prepared_x - px0, prepared_y - py0
        pweights = np.asarray([(1 - bx) * (1 - by), bx * (1 - by), (1 - bx) * by, bx * by])
        source_x = float(np.dot(pweights, [prepare_x[py0, px0], prepare_x[py0, px0 + 1], prepare_x[py0 + 1, px0], prepare_x[py0 + 1, px0 + 1]]))
        source_y = float(np.dot(pweights, [prepare_y[py0, px0], prepare_y[py0, px0 + 1], prepare_y[py0 + 1, px0], prepare_y[py0 + 1, px0 + 1]]))
        errors.append(float(np.hypot(source_x - original[0], source_y - original[1])))
    if not errors:
        raise ValueError("no diagnostic canonical point maps inside the rectified image")
    return np.asarray(errors, dtype=np.float64)


def serialize_confirmed_point(
    points_file: str | Path,
    *,
    label: str,
    u_px: int,
    v_px: int,
    image_width_px: int,
    image_height_px: int,
    coordinate_system: str,
) -> None:
    """Persist one user-confirmed click while preserving uncertainty as manual input."""
    if label not in {"static", "wave"}:
        raise ValueError("label must be static or wave")
    if not (0 <= u_px < image_width_px and 0 <= v_px < image_height_px):
        raise ValueError("clicked pixel lies outside the reference image")
    path = Path(points_file)
    document: dict[str, Any] = yaml.safe_load(path.read_text(encoding="utf-8"))
    if coordinate_system != "canonical_cam1":
        raise ValueError("formal manual clicks must use canonical_cam1")
    record = document[label]
    if record["source_coordinate_system"] != coordinate_system:
        raise ValueError("manual point coordinate-system metadata mismatch")
    if (int(record["image_width_px"]), int(record["image_height_px"])) != (image_width_px, image_height_px):
        raise ValueError("unverified resolution scaling is forbidden")
    mapping_file = (path.parent / document["mapping"]["frozen_mapping_file"]).resolve()
    canonical = np.asarray([[u_px, v_px]], dtype=np.float64)
    mapped = canonical_cam1_to_rectified(
        canonical, mapping_file=mapping_file, wass_auto_swap=bool(document["mapping"]["wass_auto_swap"])
    )[0]
    if not (0 <= mapped[0] < image_width_px and 0 <= mapped[1] < image_height_px):
        raise ValueError("confirmed canonical point maps outside the frozen rectified image")
    error = canonical_rectified_roundtrip_error(
        canonical, mapping_file=mapping_file, image_size=(image_width_px, image_height_px),
        wass_auto_swap=bool(document["mapping"]["wass_auto_swap"]),
    )[0]
    record["clicked_pixel_canonical"] = {"u_px": int(u_px), "v_px": int(v_px)}
    record["mapped_pixel_rectified"] = {"u_px": float(mapped[0]), "v_px": float(mapped[1])}
    record["mapping_roundtrip_error_px"] = float(error)
    record["confirmed_by_user"] = True
    # pixel_uncertainty_px is intentionally untouched: only the user may set it.
    path.write_text(yaml.safe_dump(document, sort_keys=False, allow_unicode=True), encoding="utf-8")
